version: '2.1'
services:
  sbsrs:
    image: biggis/sbsrs:0.1
    hostname: sbsrs
    ports:
      - "9000:9000"
    environment:
      KAFKA_SERVER: "biggiskafka_kafka_1:9092"
    external_links:
      - "biggiskafka_kafka_1"
    networks:
      - "default"
      - "biggiskafka_default"

networks:
  biggiskafka_default:
    external: true
