version: '2.1'
services:
  sbsrs:
    image: biggis/sbsrs:0.2
    hostname: sbsrs
    ports:
      - "9100:9100"
    environment:
      KAFKA_SERVER: "biggiskafka_kafka_1:9092"
# https://blog.virtualzone.de/2016/09/docker-compose-link-containers-outside-compose-file-using-external_links.html
    external_links:
      - "biggiskafka_kafka_1"
    networks:
      - "default"
      - "biggiskafka_default"

networks:
  biggiskafka_default:
    external: true
